### ISSUE TITLE
[Possible typo]  Nodes and vertices?

### ISSUE THREAD

**Issue by jcoo092** [matthewcrews/BitFieldTracking#4]
Hi Matthew,

Great blog post, but there's one thing in it that is confusing me a bit.  In a couple of places you talk about only having to deal with "20 nodes and 30 vertices".  Is that a typo?  My understanding is that vertices are the directed-graph equivalent of nodes in an undirected graph, so I'm not sure what you are meaning by that statement if it isn't a typo 😕

Anyway, thanks for the post! 😃

**Comment by matthewcrews** [comment]
You are correct. That should have been 20 nodes and 30 edges. I'll get that fixed!
